#!/bin/sh -eu

rm -f data/*
mkdir -p data

for f in *.htm; do
  sed -nre 's|.*"data/([^"]*)".*|\1|p' $f |
  while read fname; do
    cmd="$(printf "$fname" | sed 's|&| |g')"
    echo "$cmd -> $fname"
    ./he3 $cmd > data/$fname
  done
done
