function compile(v)

  func_i0 = {...
    'he3_gyro' 'he3_amass' 'he3_mmass' ...
    'const_na' 'const_kb' 'const_r' 'const_h' 'const_hbar' ...
    'const_pi' ...
    'he3_pcr' 'he3_tcr' 'he3_pabn' 'he3_tabn' ...
    'he3_psmin' 'he3_tsmin' 'he3_pa' 'he3_ta' ...
    'he3_pb' 'he3_tb' 'he3_pneel' 'he3_tneel' ...
  };

  func_i1 = {...
    'he3_pvap' 'he3_pmelt' 'he3_pmelt_gr' 'he3_tc' 'he3_tab' ...
    'he3_vm' 'he3_gammaf' 'he3_c1' 'he3_tmag' ...
    'he3_rho' 'he3_2n0' 'he3_mm' 'he3_meff' ...
    'he3_pf' 'he3_vf' 'he3_chi_n' ...
    'he3_f0a' 'he3_f0s' 'he3_f1a' 'he3_f1s' ...
    'he3_a' 'he3_gdk' 'he3_tfeff' ...
    'he3_bcsgap' 'he3_bcsgap_fast' ...
    'he3_scatt_l1a' 'he3_scatt_g0' 'he3_scatt_d0' 'he3_scatt_w0'...
    'he3_tau_r' 'he3_tau_f' ...
  };

  func_i2 = {...
    'he3_cv_n' ...
    'he3_trivgap' 'he3_z3' 'he3_z5' 'he3_z7' ...
    'he3_yosida0' 'he3_yosida0_fast' ...
    'he3_rho_nb' 'he3_chi_b' 'he3_nu_b'...
    'he3_tau_n0' 'he3_tau_n_av' 'he3_tau_nd' ...
    'he3_tau0' 'he3_tau0lt' 'he3_tau_av' 'he3_fpath' ...
    'he3_tau_dperp' 'he3_tau_dpar'...
    'he3_sdiff_nh' 'he3_sdiff_hperp' 'he3_sdiff_hpar'...
    'he3_exp_nu_b' ...
    'he3_flegg' 'he3_swvel' 'he3_swvel_par' 'he3_swvel_per' ...
    'he3_ds_exp' 'he3_dn_exp' 'he3_d_exp' 'he3_susept' ...
  };

  func_i3 = { ...
    'he3_yosida' 'he3_sdiff' 'he3_sdiff_nperp' ...
  };

  func_i4 = { ...
  };

  func_i5 = { ...
    'he3_coll_int' 'he3_coll_int_lt' 'he3_coll_int_ht' ...
  };

  % note: old octave does not support ver('Octave') call
  if (nargin < 1) v=length(ver('Octave')); end
  if v comp=@comp_octave;
  else comp=@comp_matlab; end

  for i = 1:length(func_i0) comp(func_i0{i}, 0); end
  for i = 1:length(func_i1) comp(func_i1{i}, 1); end
  for i = 1:length(func_i2) comp(func_i2{i}, 2); end
  for i = 1:length(func_i3) comp(func_i3{i}, 3); end
  for i = 1:length(func_i4) comp(func_i4{i}, 4); end
  for i = 1:length(func_i5) comp(func_i5{i}, 5); end
end
%ln -s $< $@

function comp_octave(name, narg)
  mex(['-DFUNC=' name '_ -DNARGIN=' num2str(narg)],...
       '--output', name, '-lhe3',...
       ['-L' pwd ], ['-Wl,--rpath=' pwd ],...
       'mexfunc.c');
end
function comp_matlab(name, narg)
  mex(['-DFUNC=' name '_ -DNARGIN=' num2str(narg)],...
       '-output', name, '-lhe3',...
       ['-L' pwd ], ['-Wl,--rpath=' pwd ],...
       'mexfunc.c');
end

